-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Empresa"
(
    rut character varying(10),
    nombre character varying(120),
    direccion character varying(120),
    telefono character varying(15),
    correo character varying(80),
    web character varying(50),
    CONSTRAINT empresa_pk PRIMARY KEY (rut)
);

CREATE TABLE IF NOT EXISTS public."Cliente"
(
    rut character varying(10),
    nombre character varying(120),
    correo character varying(80),
    direccion character varying(120),
    celular character varying(15),
    alta "char",
    CONSTRAINT cliente_pk PRIMARY KEY (rut)
);

CREATE TABLE IF NOT EXISTS public."TipoVehiculo"
(
    id_tipo_vehiculo numeric(12),
    nombre character varying(120),
    CONSTRAINT tipo_vehiculo_pk PRIMARY KEY (id_tipo_vehiculo)
);

CREATE TABLE IF NOT EXISTS public."Venta"
(
    folio numeric(12),
    fecha date,
    monto numeric(12),
    vehiculo_id_vehiculo numeric(12),
    cliente_rut character varying(10),
    CONSTRAINT venta_pk PRIMARY KEY (folio)
);

CREATE TABLE IF NOT EXISTS public."Vehiculo"
(
    id_vehiculo numeric(12),
    patente character varying(10),
    marca character varying(20),
    modelo character varying(20),
    color character varying(15),
    precio numeric(12),
    frecuencia_mantencion numeric(5),
    marca_id_marca numeric(12),
    tipo_vehiculo_id_tipo_vehiculo numeric(12),
    CONSTRAINT vehiculo_pk PRIMARY KEY (id_vehiculo)
);

CREATE TABLE IF NOT EXISTS public."Mantencion"
(
    id_mantencion numeric(12),
    fecha date,
    trabajos_realizados character varying(1000),
    venta_folio numeric(12),
    CONSTRAINT mantencion_pk PRIMARY KEY (id_mantencion)
);

CREATE TABLE IF NOT EXISTS public."Marca"
(
    id_marca numeric(12),
    nombre character varying(120),
    CONSTRAINT marca_pk PRIMARY KEY (id_marca)
);

ALTER TABLE IF EXISTS public."Venta"
    ADD CONSTRAINT venta_cliente_fk FOREIGN KEY (cliente_rut)
    REFERENCES public."Cliente" (rut) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Venta"
    ADD CONSTRAINT venta_vehiculo_fk FOREIGN KEY (vehiculo_id_vehiculo)
    REFERENCES public."Vehiculo" (id_vehiculo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED
    NOT VALID;


ALTER TABLE IF EXISTS public."Vehiculo"
    ADD CONSTRAINT vehiculo_marca_fk FOREIGN KEY (marca_id_marca)
    REFERENCES public."Marca" (id_marca) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vehiculo"
    ADD CONSTRAINT vehiculo_tipo_vehiculo_fk FOREIGN KEY (tipo_vehiculo_id_tipo_vehiculo)
    REFERENCES public."TipoVehiculo" (id_tipo_vehiculo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Mantencion"
    ADD CONSTRAINT mantencion_venta_pk FOREIGN KEY (venta_folio)
    REFERENCES public."Venta" (folio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;