-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Empresa"
(
    rut character varying(10),
    nombre character varying(120),
    direccion character varying(120),
    telefono character varying(15),
    correo character varying(80),
    web character varying(50),
    CONSTRAINT empresa_pk PRIMARY KEY (rut)
);

CREATE TABLE IF NOT EXISTS public."Cliente"
(
    rut character varying(10),
    nombre character varying(120),
    correo character varying(80),
    direccion character varying(120),
    celular character varying(15),
    CONSTRAINT cliente_pk PRIMARY KEY (rut)
);

CREATE TABLE IF NOT EXISTS public."Herramienta"
(
    id_herramienta numeric(12),
    nombre character varying(120),
    precio_dia numeric(12),
    CONSTRAINT herramienta_pk PRIMARY KEY (id_herramienta)
);

CREATE TABLE IF NOT EXISTS public."Arriendo"
(
    folio numeric(12),
    fecha date,
    dias numeric(5),
    valor_dia numeric(12),
    garantia character varying(30),
    herramienta_id_herramienta numeric(12),
    cliente_rut character varying(10),
    CONSTRAINT arriendo_pk PRIMARY KEY (folio)
);

ALTER TABLE IF EXISTS public."Arriendo"
    ADD CONSTRAINT arriendo_herramienta_fk FOREIGN KEY (herramienta_id_herramienta)
    REFERENCES public."Herramienta" (id_herramienta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Arriendo"
    ADD CONSTRAINT arriendo_cliente_fk FOREIGN KEY (cliente_rut)
    REFERENCES public."Cliente" (rut) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;